global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'pi_network_monitor_http_sd'
    http_sd_configs:
      - url: 'https://pi-registrar:5000/targets'
        refresh_interval: 30s
        tls_config:
          ca_file: '/etc/prometheus/certs/pi_registrar_server_public_cert.pem'
          # Add this line:
          server_name: 'AeroScan'
    relabel_configs:
      - source_labels: [pi_identifier]
        regex: (.+)
        target_label: instance
