global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'pi_network_monitor_http_sd'
    http_sd_configs:
      # Use https and the Docker service name (pi-registrar) and internal port (5000)
      - url: 'https://pi-registrar:5000/targets'
        refresh_interval: 30s
        # Configure Prometheus to trust your self-signed certificate
        tls_config:
          # Path to the CA cert (or self-signed server cert) inside the Prometheus container
          ca_file: '/etc/prometheus/certs/pi_registrar_server_public_cert.pem'
          # If the CN in your cert doesn't match 'pi-registrar' (service name),
          # you might need to uncomment and set server_name, e.g.:
          # server_name: 'pi-registrar-internal' # Or whatever CN you used in setup_server.sh
    relabel_configs:
      - source_labels: [pi_identifier]
        regex: (.+)
        target_label: instance
