global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'pi_network_monitor_http_sd'
    http_sd_configs:
      # Use the service name and INTERNAL port defined in docker-compose
      - url: 'http://pi-registrar:5000/targets'
        refresh_interval: 30s # How often Prometheus asks the registrar for targets
    # Optional: Relabeling
    relabel_configs:
      - source_labels: [pi_identifier]
        regex: (.+)
        target_label: instance
